# This file is used to assist development

services:
  agent:
    build: .
    entrypoint: [ "sleep", "infinity" ]
    init: true
    volumes:
      - ./:/app
      - ./tmp/deploy-keys:/deploy-keys:ro
      - .:/local-repos/asset-manager:ro
    environment:
      - |
        BUCKET_CONFIG={
          "temp": {
            "endpoint_url": "http://minio:9000",
            "access_key_id": "minioaccess",
            "secret_key": "miniosecret",
            "bucket_name": "asset-temp"
          },
          "perm": {
            "endpoint_url": "http://minio:9000",
            "access_key_id": "minioaccess",
            "secret_key": "miniosecret",
            "bucket_name": "asset-perm"
          },
          "off-perm": {
            "endpoint_url": "http://minio:9000",
            "access_key_id": "minioaccess",
            "secret_key": "miniosecret",
            "bucket_name": "asset-off-perm"
          }
        }
      - |
        REPO_CONFIG={
          "repos": [
            {
              "type": "git+https",
              "url": "https://github.com/octocat/Hello-World.git"
            }
          ]
        }
    depends_on:
      minio-init:
        condition: service_completed_successfully

  minio:
    image: minio/minio:RELEASE.2024-11-07T00-52-20Z
    environment:
      MINIO_ACCESS_KEY: minioaccess
      MINIO_SECRET_KEY: miniosecret
    command: server /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 2s
      timeout: 5s
      retries: 20

  minio-init:
    image: minio/mc
    entrypoint: [ "sh", "-c" ]
    command:
      - |
        mc alias set minio http://minio:9000 minioaccess miniosecret
        mc mb --ignore-existing minio/asset-temp
        mc mb --ignore-existing minio/asset-perm
        mc mb --ignore-existing minio/asset-off-perm
    depends_on:
      minio:
        condition: service_healthy


